# Standard HTTP setup for the Ebbinghaus Reminder frontend
server {
    listen 80;           # Listen for incoming traffic on the default HTTP port
    server_name _;       # Respond to any domain or IP (wildcard)

    # Main location block for the React SPA
    location / {
        root   /usr/share/nginx/html;      # Where the 'dist' files are stored in Docker
        index  index.html index.htm;       # Default file to serve
        
        # KEY FOR REACT ROUTER: 
        # If a file ($uri) or folder ($uri/) isn't found, 
        # redirect everything to index.html so React can handle the route.
        try_files $uri $uri/ /index.html;
    }

}