version: '3.8'
services:
  ebbinghaus-frontend:
    build:
      context: .
    platform: linux/arm64
    image: ratverg/ebbinghaus-frontend:latest
    container_name: ebbinghaus-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    external: true  