server {
    listen 80;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line tells Nginx: 
        # "If you can't find the file, just give them index.html"
        try_files $uri $uri/ /index.html;
    }
}