version: '3.8'

services:
  ebbinghaus-backend:
    image: ratverg/ebbinghaus-backend:latest
    platform: linux/arm64 
    build: .
    container_name: ebbinghaus-backend
    #port expose for local use
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    #Memory limit for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
    #insert plug to my cloudflare network
    networks:
      - cloudflare_net

networks:
  cloudflare_net:
    external: true