package ru.ratverg.ar_back.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import ru.ratverg.ar_back.DTO.ApiError;
import ru.ratverg.ar_back.exception.*;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

@RestControllerAdvice
public class GlobalExceptionHandler {

    //build standard response status error
    // so every error will have JSON body
    private ResponseEntity<ApiError> buildError (
            String code,
            String message,
            HttpStatus status,
            Map<String, String> errors
    ) {
        return ResponseEntity
                .status(status)
                .body(new ApiError(
                        code,
                        message,
                        status.value(),
                        Instant.now(),
                        errors));
    }

    @ExceptionHandler(AuthCodeExpiredException.class)
    public ResponseEntity<ApiError> handleExpiredCode(AuthCodeExpiredException e) {
        return buildError(
                "AUTH_CODE_EXPIRED",
                e.getMessage(),
                HttpStatus.GONE,
                null
        );
    }

    @ExceptionHandler(DateNotFoundException.class)
    public ResponseEntity<ApiError> handleDateNotFoundException(DateNotFoundException e) {
        return buildError(
                "AUTH_CODE_EXPIRED",
                e.getMessage(),
                HttpStatus.GONE,
                null
        );
    }

    @ExceptionHandler(AuthCodeNotFoundException.class)
    public ResponseEntity<ApiError> handleAuthCodeNotFound(AuthCodeNotFoundException e) {
        return buildError(
                "AUTH_CODE_NOT_FOUND",
                e.getMessage(),
                HttpStatus.NOT_FOUND,
                null
        );
    }

    @ExceptionHandler(AuthCodeException.class)
    public ResponseEntity<ApiError> handleAuthCode(AuthCodeException e) {
        return buildError(
                "AUTH_CODE_INVALID",
                e.getMessage(),
                HttpStatus.FORBIDDEN,
                null
        );
    }

    @ExceptionHandler(TGUserNotFoundException.class)
    public ResponseEntity<ApiError> handleTGUserNotFound(TGUserNotFoundException e) {
        return buildError(
                "TG_USER_NOT_FOUND",
                e.getMessage(),
                HttpStatus.NOT_FOUND,
                null
        );
    }
    @ExceptionHandler(NotificationNotFoundException.class)
    public ResponseEntity<ApiError> handleNotificationNotFound(NotificationNotFoundException e) {
        return buildError(
                "NOTIFICATION_NOT_FOUND",
                e.getMessage(),
                HttpStatus.NOT_FOUND,
                null
        );
    }

    //handle validation error
    //handle all exceptions generated by DTO annotations like this "@NotBlank (message = "Username can not be empty")"
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiError> handleValidationExceptions(MethodArgumentNotValidException e){
        //.getBinding result - it's like a results of Data Binding - the process of transforming data from request to DTO fields. like
        // - "username" - ok
        // - "email" - not ok, not null
        //Yes, we will get array of this errors, and we can stream them

        Map<String, String> errorsMap = e.getBindingResult().getFieldErrors().stream()
                .collect(Collectors.toMap(
                        x -> x.getField(),
                        x -> x.getDefaultMessage(),
                        (a, b) -> a //if there are two, get first
                ));

        return buildError(
                "VALIDATION_ERROR",
                "Validation failed",
                HttpStatus.BAD_REQUEST,
                errorsMap
                );
    }

    //all other unlisted exceptions
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiError> handleUnknown(Exception e) {

        return buildError(
                "INTERNAL_ERROR",
                "Unexpected error: " + e.getMessage(),
                HttpStatus.INTERNAL_SERVER_ERROR,
                null
        );
    }

}
